
hola_mundo: hola_mundo.o ../funcion2/funcion.o 
	gcc -I../funcion2 hola_mundo.o ../funcion2/funcion.o -o hola_mundo.out

clean:
	rm hola_mundo.out *~

# busca los .c en los directorios pero no sabe buscar los .h que esten en otros directorios
